name = "cf-simply-blog"
pages_build_output_dir = "./dist"
compatibility_date = "2025-02-05"

[[d1_databases]]
binding = "DB"
database_name = "blogs-db"
database_id = "xxxx-xxxx-xxxx-xxxx-xxxx"

[vars]
API_KEY = "1234567asdf"